version: '3'

services:
  accountsdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: accountsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
    networks:
      - mandaleazy

  accounts:
    image: "sankha169/accounts"
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountservice
    depends_on:
      - accountsdb
    networks:
      - mandaleazy

networks:
  mandaleazy:
