server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://accountsdb:3306/accountservice
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: test

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        ddl-auto: update
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
